const savedData = [
    {
        id: 1,
        latitude: 35.6895,
        longitude: 139.6917,
        title: 'Tokyo Skytree',
        description: 'Intermediate',
        description2: 'Explore the iconic Tokyo Skytree, a towering landmark offering breathtaking views of the cityscape. The observation deck provides a panoramic experience, allowing you to see Tokyos modern architecture and historic landmarks. Enjoy the vibrant atmosphere and consider visiting the nearby Sumida Aquarium for a unique aquatic experience.',
        distance: 4800,
        rating: 4.7,
        est_time: 60,
        image: require('../assets/images/hiking21.jpg'),
    },
    {
        id: 2,
        latitude: 37.7749,
        longitude: -122.4194,
        title: 'Golden Gate Park',
        description: 'Beginner',
        description2: 'Golden Gate Park is a fantastic destination for beginners, offering a mix of nature and recreational activities. Stroll through the parks lush greenery, visit the Japanese Tea Garden, and discover the iconic Conservatory of Flowers. The well-maintained paths make it suitable for all ages, providing a peaceful escape within the heart of San Francisco.',
        distance: 3700,
        rating: 3.9,
        est_time: 75,
        image: require('../assets/images/hiking22.jpg'),
    },
    {
        id: 3,
        latitude: 40.7831,
        longitude: -73.9712,
        title: 'Central Park',
        description: 'Intermediate',
        description2: 'Central Park offers an intermediate-level hiking experience in the heart of New York City. Wander through iconic locations like Bethesda Terrace and Bow Bridge, surrounded by the parks diverse landscapes. Enjoy the urban oasis, spot various wildlife, and consider exploring the Central Park Zoo for an added adventure. The mix of city views and natural beauty makes it a must-visit destination.',
        distance: 8.2,
        rating: 2500,
        est_time: 90,
        image: require('../assets/images/hiking23.jpg'),
    },
    {
        id: 4,
        latitude: 51.5099,
        longitude: -0.1336,
        title: 'The British Museum',
        description: 'Intermediate',
        description2: 'Embark on an intermediate-level urban exploration around The British Museum. This cultural hub offers a unique blend of history and art. Wander through the exhibits, marvel at ancient artifacts, and soak in the rich cultural heritage. The well-lit interiors and intriguing collections make it a captivating experience for history enthusiasts and casual visitors alike.',
        distance: 6500,
        rating: 4.5,
        est_time: 80,
        image: require('../assets/images/hiking24.jpg'),
    },
    {
        id: 5,
        latitude: -33.8688,
        longitude: 151.2093,
        title: 'Sydney Harbour Bridge Walk',
        description: 'Advanced',
        description2: 'For the adventurous hiker, the Sydney Harbour Bridge Walk offers a thrilling urban experience. Traverse the iconic bridge, enjoying panoramic views of Sydney Harbour and the Opera House. The ascent and descent challenges your fitness, providing a sense of accomplishment. Do not forget to capture stunning photos of the city skyline and harbor during this advanced-level urban hike.',
        distance: 6000,
        rating: 3.4,
        est_time: 120,
        image: require('../assets/images/hiking25.jpg'),
    },
];


export default savedData;
